add checks for compilers, flex/bison at configure stage

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19,7 +19,6 @@ compiler="gnu"
 cc="gcc -Wno-unused-result"
 cxx="g++"
 mpicc="mpicc"
-fc="gfortran"
 cstdflags=""
 optflags="-g -Ofast -mtune=native"
 
@@ -164,6 +163,117 @@ else
    make_shared=-shared
    lm=-lm
 fi
+
+#--------------------------------------------------------------------------
+#  Test if the C compiler works:
+#--------------------------------------------------------------------------
+
+cat <<EOF >testp.c
+#include <stdio.h>
+int main()
+{
+   printf( "testing a C program\n" );
+}
+EOF
+
+printf "Testing $cc: "
+# echo "     $cc  -o testp testp.c"
+$cc -o testp testp.c
+./testp | grep "testing a C program" > /dev/null
+status=$?
+
+if [ $status -gt 0 ]; then
+    echo "Error: Unable to compile a C program using $cc"
+    echo "       Please check your compiler settings or configure flags."
+    exit 1
+fi
+echo "OK"
+/bin/rm -f testp.c testp testp
+
+#--------------------------------------------------------------------------
+#  Test if the Fortran compiler works:
+#--------------------------------------------------------------------------
+
+cat <<EOF >testp.f
+      program testf
+      write(6,*) 'testing a Fortran program'
+      end program testf
+EOF
+
+printf "Testing $fc: "
+#echo "     $fc -o testp testp.f "
+$fc -o testp testp.f
+./testp | grep "testing a Fortran program" > /dev/null
+status=$?
+
+if [ $status -gt 0 ]; then
+    echo "Error: Unable to compile a Fortran program using $fc "
+    echo "       Please check your compiler settings and configure flags."
+    exit 1
+fi
+echo "OK"
+/bin/rm -f testp.f testp testp
+
+#--------------------------------------------------------------------------
+#  Test if flex is available and works
+#--------------------------------------------------------------------------
+
+  printf "Testing flex: "
+  cat <<EOF >testp.l
+%{
+
+
+%}
+%%
+
+ddm[=\ ][^\ \n\t,]+         { ECHO; ddm = 1;}
+
+%%
+EOF
+
+flex -t testp.l | grep ddm  > /dev/null
+status=$?
+
+if [ $status -gt 0 ]; then
+    echo ""
+    echo "Error: Unable to run flex; this is required for NAB and sff."
+    echo "       Please check your PATH, or install the program."
+    echo ""
+    exit 1
+else
+    echo "OK"
+fi
+/bin/rm -f testp.l
+
+#--------------------------------------------------------------------------
+#  Test if bison is available and works
+#--------------------------------------------------------------------------
+
+  printf "Testing bison: "
+  cat <<EOF >testp.y
+%{
+static int curItemNo, curValueNo, itemIndex;
+%}
+%token NUMBER
+%%
+term: NUMBER  { curItemNo = 1; }
+
+%%
+EOF
+
+bison -y testp.y
+status=$?
+
+if [ $status -gt 0 ]; then
+    echo ""
+    echo "Error: Unable to run bison."
+    echo "       Please check your PATH, or install the program."
+    echo ""
+    exit 1
+else
+    echo "OK"
+fi
+/bin/rm -f testp.y y.tab.c
 
 #--------------------------------------------------------------------------
 #  Configure the MKL or GOTO etc libraries for BLAS/LAPACK.
