add netcdf capability (from msander)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12,7 +12,6 @@ mpi=
 mpiflag=""
 requested_help="no"
 bintraj=""
-netcdflib=""
 openblas="no"
 
 compiler="gnu"
@@ -42,6 +41,8 @@ ciflib=""
 installtype="serial"
 inc="-I$nabchome/include"
 
+netcdflib="-lnetcdf"
+bintraj="-DBINTRAJ"
 flibs_arch="-lgfortran -w"
 
 #  process command-line flags:
@@ -56,9 +57,6 @@ for var in "$@"; do
         --openmp)
             ompflag='-fopenmp -DOPENMP';
             openmp="yes";;
-        --netcdf)
-            netcdflib="-lnetcdf"
-            bintraj="-DBINTRAJ";;
         --cif)
             ciftarget="libcifparse"
             ciflib="-lcifparse"
@@ -96,7 +94,6 @@ done
 
 if [ "$requested_help" = "yes" ] ; then
 	printf " --verbose      give build details, otherwise be more silent\n"
-	printf " --netcdf       enable NetCDF support (requires libnetcdf)\n"
 	printf " --intel        use Intel compiler; default is gcc\n"
 	printf " --clang        use clang compiler; default is gcc\n"
 	printf " --mpi          prepare for MPI build\n"
@@ -274,6 +271,66 @@ else
     echo "OK"
 fi
 /bin/rm -f testp.y y.tab.c
+
+#--------------------------------------------------------------------------
+#  Configure and build netcdf:
+#--------------------------------------------------------------------------
+if [ ! -s "lib/libnetcdf.a" ]; then
+   cd src/netcdf-c-4.7.2
+   printf "Configuring the NetCDF C interface..."
+   make clean > /dev/null 2>&1
+   ./configure CC="$cc" CFLAGS="-fPIC" LDFLAGS="" \
+      --prefix=$nabchome --disable-netcdf-4 --disable-dap \
+      --disable-shared --disable-doxygen > ../netcdf_c.config.log 2>&1
+   ncerror=$?
+   if [ $ncerror -gt 0 ]; then
+       echo "Error: NetCDF configure failed!  Check netcdf_c.config.log"
+       exit 1
+   else
+       echo "OK"
+   fi
+   # The NetCDF C interface MUST be present prior to configuring the
+   # Fortran interface, so build it now.
+   printf "Compiling the NetCDF C interface..."
+   make install > ../netcdf_c.compile.log 2>&1
+   if [ $? -ne 0 ]; then
+       echo "Error: NetCDF compile failed!  Check netcdf_c.compile.log"
+       exit 1
+   else
+       echo "OK"
+   fi
+   # NetCDF Fortran configure/build
+   cd ../netcdf-fortran-4.5.2
+   # The NetCDF Fortran config script will need access to the C library.
+   export LD_LIBRARY_PATH="$nabchome/lib:$LD_LIBRARY_PATH"
+   printf "Configuring the NetCDF Fortran interface..."
+   make clean > /dev/null 2>&1
+   ./configure  CC="$cc" CFLAGS="-fPIC" \
+                  LDFLAGS="-L$nabchome/lib $ldflags" \
+                  CPPFLAGS="-I$nabchome/include" \
+                  FC="$fc" FCFLAGS="" \
+                  F77="$fc" FFLAGS="-fPIC" --disable-shared  --disable-doxygen \
+                  --prefix=$nabchome >> ../netcdf_f.config.log 2>&1
+   ncerror=$?
+   if [ $ncerror -gt 0 ]; then
+       echo "Error: NetCDF configure failed!  Check netcdf_f.config.log"
+       exit 1
+   else
+       echo "OK"
+   fi
+   # Build the fortran interface
+   printf "Compiling the NetCDF Fortran interface..."
+   make install > ../netcdf_f.compile.log 2>&1
+   if [ $? -ne 0 ]; then
+     echo "Error: NetCDF Fortran compile failed!  Check netcdf_f.compile.log"
+     exit 1
+   else
+       echo "OK"
+   fi
+   cd ../..
+else
+   echo "Using the existing netcdf libraries"
+fi
 
 #--------------------------------------------------------------------------
 #  Configure the MKL or GOTO etc libraries for BLAS/LAPACK.
